stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: dev
    pool:
      vmImage: 'Ubuntu-22.04'
    environment:
      name: Development
      resourceType: VirtualMachine
      tags: bluevm
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Downloading the source code from Azure blob storage container to the Azure VM..."
              sudo az storage blob download --account-name bluegreendemo --container-name application-container --name test-application.zip --file /opt/test-application
              echo "Extracting the source code and setting up the application to the Azure VM..."
